"""Hugging Face Daily Papers client.

Endpoint: https://huggingface.co/api/papers?date=YYYY-MM-DD

HF returns a curated list of ~20-50 trending AI papers per day with title,
authors, summary (raw abstract), an `ai_summary` (TLDR generated by HF),
upvotes, and the arxiv id. We pull the last N days and filter by query.

Free, no key.
"""

from __future__ import annotations

import logging
from datetime import date, timedelta
from typing import Iterable, Optional

from ..config import Settings
from ..state import Paper
from ._http import get_client, safe_get

log = logging.getLogger(__name__)


def _parse(p: dict, year_filter: Optional[tuple[int, int]]) -> Optional[Paper]:
    arxiv_id = (p.get("id") or "").strip()
    title = (p.get("title") or "").strip()
    if not title:
        return None

    published_at = (p.get("publishedAt") or "")[:10]
    year = None
    if len(published_at) >= 4 and published_at[:4].isdigit():
        year = int(published_at[:4])
    if year_filter and year and not (year_filter[0] <= year <= year_filter[1]):
        return None

    # Prefer `summary` (full abstract) over `ai_summary` (TLDR).
    abstract = (p.get("summary") or p.get("ai_summary") or "").strip()

    authors = [a.get("name", "") for a in (p.get("authors") or []) if a.get("name")]

    url = f"https://arxiv.org/abs/{arxiv_id}" if arxiv_id else ""
    upvotes = p.get("upvotes")
    venue = "Hugging Face Daily Papers"

    return Paper(
        title=title,
        authors=authors,
        year=year,
        abstract=abstract,
        venue=venue,
        url=url,
        arxiv_id=arxiv_id,
        categories=[],
        citation_count=upvotes,  # HF upvotes as a proxy "score"
        source="huggingface",
        extra={"upvotes": upvotes} if upvotes is not None else {},
    )


def search_huggingface(
    settings: Settings,
    queries: Iterable[str],
    *,
    max_per_query: Optional[int] = None,
    years: Optional[tuple[int, int]] = None,
    lookback_days: int = 14,
) -> list[Paper]:
    """Pull HF daily papers for the last `lookback_days` days and filter by query.

    HF's API only exposes *trending* daily papers, not full-text search, so we
    over-fetch and substring-filter on the title + abstract.
    """
    cap = max_per_query if max_per_query is not None else settings.huggingface_max_per_query
    q_list = [q.strip().lower() for q in queries if q.strip()]
    out: list[Paper] = []
    seen: set[str] = set()

    today = date.today()
    with get_client(settings) as client:
        for delta in range(lookback_days):
            d = today - timedelta(days=delta)
            resp = safe_get(
                client,
                "https://huggingface.co/api/papers",
                params={"date": d.isoformat()},
            )
            if resp is None:
                continue
            try:
                papers = resp.json() or []
            except Exception as exc:  # pragma: no cover
                log.warning("HF JSON parse failed for %s: %s", d, exc)
                continue

            kept = 0
            for p in papers:
                paper = _parse(p, years)
                if paper is None or not paper.arxiv_id:
                    continue
                # Substring filter against the queries.
                haystack = (paper.title + " " + paper.abstract).lower()
                if q_list and not any(q in haystack for q in q_list):
                    continue
                if paper.arxiv_id in seen:
                    continue
                seen.add(paper.arxiv_id)
                out.append(paper)
                kept += 1
                if kept >= cap:
                    break

    return out
